In [41]:
import numpy as np
import pandas as pd

In [42]:
data = pd.read_csv('table.csv')

In [43]:
data.head(5)

,Customer_ID,Age_Group,Education_Level,Income_Level,Satisfaction_Rating,City,Gender,Product_Rating
0,C001,Young,High School,Low,Very Satisfied,New York,Male,5
1,C002,Middle-Aged,Bachelor's,Medium,Satisfied,London,Female,4
2,C003,Senior,Master's,High,Neutral,Tokyo,Male,3
3,C004,Young,PhD,High,Dissatisfied,Berlin,Female,2
4,C005,Middle-Aged,High School,Low,Very Dissatisfied,Mumbai,Male,1

In [44]:
data.iloc[:, 1:5]

     Age_Group Education_Level Income_Level Satisfaction_Rating
0        Young     High School          Low      Very Satisfied
1  Middle-Aged      Bachelor's       Medium           Satisfied
2       Senior        Master's         High             Neutral
3        Young             PhD         High        Dissatisfied
4  Middle-Aged     High School          Low   Very Dissatisfied
5          ...             ...          ...                 ...

In [45]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(data.iloc[:, 1:5], data.iloc[:, -2], test_size=0.2)

In [50]:
from sklearn.preprocessing import OrdinalEncoder, LabelEncoder

In [51]:
X_train.head()

     Age_Group Education_Level Income_Level Satisfaction_Rating
4  Middle-Aged     High School          Low   Very Dissatisfied
2       Senior        Master's         High             Neutral
0        Young     High School          Low      Very Satisfied
3        Young             PhD         High        Dissatisfied

In [52]:
oe = OrdinalEncoder(categories=[["Young", "Middle-Aged", "Senior"],
                                ["High School", "Bachelor's", "Master's", "PhD"],
                                ["Low", "Medium", "High"],
                              ["Very Dissatisfied", "Dissatisfied", "Neutral", "Satisfied", "Very Satisfied"]])

In [54]:
# ordinal_cols = ['Age_Group', 'Education_Level', 'Income_Level', 'Satisfaction_Rating']

In [57]:
oe.fit(X_train)

OrdinalEncoder(categories=[['Young', 'Middle-Aged', 'Senior'],
                           ['High School', "Bachelor's", "Master's", 'PhD'],
                           ['Low', 'Medium', 'High'],
                           ['Very Dissatisfied', 'Dissatisfied', 'Neutral',
                            'Satisfied', 'Very Satisfied']])

In [61]:
oe.fit_transform(X_test)

ValueError: Found unknown categories ['...'] in column 0 during fit

In [60]:
X_train = oe.transform(X_train)
X_test = oe.transform(X_test)

C:\Users\Admin\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but OrdinalEncoder was fitted with feature names
  warnings.warn(

TypeError: ufunc 'isnan' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''

In [59]:
X_train

array([[1., 0., 0., 0.],
       [2., 2., 2., 2.],
       [0., 0., 0., 4.],
       [0., 3., 2., 1.]])