In [1]:
import numpy as np
import pandas as pd

In [33]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder, MinMaxScaler
from sklearn.impute import SimpleImputer
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline, make_pipeline
from sklearn.feature_selection import SelectKBest, chi2
from sklearn.tree import DecisionTreeClassifier

In [34]:
data = pd.read_csv('train.csv')

In [35]:
data.head(3)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S

In [36]:
data.drop(columns=['PassengerId', 'Name', 'Ticket', 'Cabin'], inplace=True)

In [37]:
# TTS
X_train, X_test, Y_train, Y_test = train_test_split(data.drop(columns=['Survived']),
                                                    data['Survived'],
                                                    test_size=0.2,
                                                    random_state=42)

In [38]:
X_train.head(4)

     Pclass   Sex   Age  SibSp  Parch     Fare Embarked
331       1  male  45.5      0      0  28.5000        S
733       2  male  23.0      0      0  13.0000        S
382       3  male  32.0      0      0   7.9250        S
704       3  male  26.0      1      0   7.8542        S

# Transformation and Scaling

In [39]:
# Imputation Transformer
trf1 = ColumnTransformer([
    ('imputer_age', SimpleImputer(), [2]),
    ('impute_embarked', SimpleImputer(strategy='most_frequent'), [6])
], remainder='passthrough')

In [40]:
# OneHotEncoding
trf2 = ColumnTransformer([
    ('ohe_sex_embarked', OneHotEncoder(sparse_output=False, handle_unknown='ignore'), [1,6])
], remainder='passthrough')

In [41]:
# Feature Scaling
trf3 = ColumnTransformer([
    ('scale', MinMaxScaler(), slice(0, 10))
     ])

In [42]:
# Feature Selection
trf4 = SelectKBest(score_func=chi2, k=8)

In [43]:
# Train Model
trf5 = DecisionTreeClassifier()

# Create Pipline

In [45]:
pipe = make_pipeline(trf1, trf2, trf3, trf4, trf5)

In [51]:
# pipe.fit(X_train, Y_train)
pipe.fit_transform(X_test)

AttributeError: This 'Pipeline' has no attribute 'fit_transform'

In [47]:
# Predict
Y_pred = pipe.predict(X_test)

In [48]:
Y_pred

array([1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1,
       0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1,
       0, 0, 0])

In [49]:
from sklearn.metrics import accuracy_score
Acc = accuracy_score(Y_test, Y_pred)
print(Acc)

0.6256983240223464