In [1]:
print("working");

working

In [1]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score, root_mean_squared_error

In [2]:
data = {
    'CGPA': [6.5, 7.0, 7.5, 8.0, 8.5, 9.0, 9.5, 6.8, 7.8, 8.2, 9.2],
    'Package': [4.5, 6.0, 7.0, 8.5, 9.5, 12.0, 13.5, 5.5, 8.0, 9.0, 11.5]
}

df = pd.DataFrame(data)
df.head()

   CGPA  Package
0   6.5      4.5
1   7.0      6.0
2   7.5      7.0
3   8.0      8.5
4   8.5      9.5

In [14]:
x = df[['CGPA']]; #Feature
y = df['Package'] #Target

X_train, X_test, Y_train, Y_test = train_test_split(x, y, test_size=0.2, random_state=42)

X_train

    CGPA
10   9.2
2    7.5
1    7.0
8    7.8
4    8.5
7    6.8
3    8.0
6    9.5

In [16]:
model = LinearRegression()
model.fit(X_train, Y_train)

y_pred = model.predict(X_test)

In [18]:
# Calculate All Metrices
mae = mean_absolute_error(Y_test, y_pred)
mse = mean_squared_error(Y_test, y_pred)
rmse = np.sqrt(mse)
r2 = r2_score(Y_test, y_pred)

print(f"MAE Score: : {mae: .4f}")
print(f"MSE Score: : {mse: .4f}")
print(f"RMSE Score: {rmse: .4f}")
print(f"R2 Score: {r2: .4f} ({r2*100: .2f}%)")

MAE Score: :  0.2869
MSE Score: :  0.1449
RMSE Score:  0.3807
R2 Score:  0.9847 ( 98.47%)