In [16]:
import numpy as np
import pandas as pd

In [17]:
from sklearn.impute import SimpleImputer #Used to fill the Null(NaN) values
from sklearn.preprocessing import OrdinalEncoder
from sklearn.preprocessing import OneHotEncoder

In [18]:
data = pd.read_csv('covid_toy.csv')

In [19]:
data.head(3)

   age gender  fever cough     city has_covid
0   60   Male  103.0  Mild  Kolkata        No
1   27   Male  100.0  Mild    Delhi       Yes
2   42   Male  101.0  Mild    Delhi        No

In [20]:
data.isnull().sum()

age           0
gender        0
fever        10
cough         0
city          0
has_covid     0
dtype: int64

In [21]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(data.drop(columns=['has_covid']), data['has_covid'], test_size = 0.2)

In [22]:
X_train

    age  gender  fever   cough       city
57   49  Female   99.0  Strong  Bangalore
26   19  Female  100.0    Mild    Kolkata
48   66    Male   99.0  Strong  Bangalore
49   44    Male  104.0    Mild     Mumbai
64   42    Male  104.0    Mild     Mumbai
..  ...     ...    ...     ...        ...
59    6  Female  104.0    Mild    Kolkata
54   60  Female   99.0    Mild     Mumbai
66   51    Male  104.0    Mild    Kolkata
14   51    Male  104.0    Mild  Bangalore
86   25    Male  104.0    Mild  Bangalore

[80 rows x 5 columns]

# Without using Column Transformer

In [23]:
si = SimpleImputer()
X_train_fever = si.fit_transform(X_train[['fever']])

X_test_fever = si.fit_transform(X_test[['fever']])

In [24]:
# Ordinal Encoding -> Cough Col
oe = OrdinalEncoder(categories=[['Mild', 'Strong']])

# On Train Data
X_train_cough = oe.fit_transform(X_train[['cough']])

# Also on test data
X_test_cough = oe.fit_transform(X_test[['cough']])

In [25]:
# OneHotEncoding -> Gender, City
ohe = OneHotEncoder()

# Train data
X_train_gender_city = ohe.fit_transform(X_train[['gender', 'city']])

# Test data
X_test_gender_city = ohe.fit_transform(X_test[['gender', 'city']])

In [26]:
# Extracting Age
X_train_age = X_train.drop(columns=['gender', 'fever', 'cough', 'city']).values

# On test data
X_test_age = X_test.drop(columns=['gender', 'fever', 'cough', 'city']).values

In [27]:
X_train_age.ndim

2

In [28]:
X_train_gender_city.ndim

2

In [29]:
# # Concatenating the derived data
# X_train_transformed = np.concatenate((X_train_age, X_train_fever, X_train_gender_city, X_train_cough),axis=1)

# With Column Transforming

In [30]:
from sklearn.compose import ColumnTransformer

In [31]:
transformer = ColumnTransformer(transformers=[
    ('nigga1', SimpleImputer(), ['fever']),
    ('nigga2', OrdinalEncoder(categories=[['Mild', 'Strong']]),['cough']),
    ('nigga3', OneHotEncoder(sparse_output=False, drop='first'), ['gender', 'city'])
], remainder='passthrough')

In [32]:
transformer.fit_transform(X_train).shape

(80, 7)

In [33]:
transformer.transform(X_test).shape

(20, 7)

In [35]:
# Pattern for Column Transformation
# Import -> Analyze -> Train_Test_Split/Drop Final Column -> Use Column Tranformer -> Create Tuples -> Fit Transform Train Data -> Transform Test Data

In [36]:
print(X_train.shape)

(80, 5)