In [1]:
print("Working")

Working

In [ ]:
# Multivairate Imputation -> using data of other columns as well to get fillup the missing values (if the columns are realted to each other)
# Ex: Predicting salary according to this: class, experience, skills, communication_skills, etc. Here these are different columns which helps to predict the salary. -> Multivariate Analysis 

# KNN Imputer
    # Uniform Weights -> taking average of 2 feats
    # Distance Weights -> multiplying by taking reciprocal of the distance ((1 / distance) * weight)

In [22]:
import numpy as np 
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.impute import SimpleImputer, KNNImputer
from sklearn.linear_model import LogisticRegression

from sklearn.metrics import accuracy_score

In [23]:
data = pd.read_csv('train.csv', usecols=['Age', 'Pclass', 'Fare', 'Survived'])
data.head(5)

   Survived  Pclass   Age     Fare
0         0       3  22.0   7.2500
1         1       1  38.0  71.2833
2         1       3  26.0   7.9250
3         1       1  35.0  53.1000
4         0       3  35.0   8.0500

In [24]:
data.isnull().mean()*100

Survived     0.00000
Pclass       0.00000
Age         19.86532
Fare         0.00000
dtype: float64

In [25]:
x = data.drop(columns=['Survived'])
y = data['Survived']

In [26]:
X_train, X_test, Y_train, Y_test = train_test_split(x, y, test_size=0.2, random_state=42)
X_train

     Pclass   Age      Fare
331       1  45.5   28.5000
733       2  23.0   13.0000
382       3  32.0    7.9250
704       3  26.0    7.8542
813       3   6.0   31.2750
..      ...   ...       ...
106       3  21.0    7.6500
270       1   NaN   31.0000
860       3  41.0   14.1083
435       1  14.0  120.0000
102       1  21.0   77.2875

[712 rows x 3 columns]

In [27]:
knn = KNNImputer(n_neighbors=2, weights='distance')
X_train_knn = knn.fit_transform(X_train)
X_test_knn = knn.transform(X_test)

In [31]:
lr = LogisticRegression()

lr.fit(X_train_knn, Y_train)
y_pred = lr.predict(X_train_knn)

y_pred = lr.predict(X_test_knn)   # 712 predictions
acc = accuracy_score(Y_test, y_pred)  # Y_test has 179 values
acc

0.7374301675977654

### Comparing the results with SimpleImputer

In [38]:
si = SimpleImputer(strategy='mean')

X_train_si = si.fit_transform(X_train)
X_test_si = si.transform(X_test)

In [39]:
lr = LogisticRegression()

lr.fit(X_train_si, Y_train)
y_pred2 = lr.predict(X_test_si)

acc2 = accuracy_score(y_pred2, Y_test)
acc2

0.7374301675977654