In [ ]:
print("Working")
# Ways to fill the values: 1. Mean/Median | 2. Arbitary | 3. End of Distribution (formula used (mean*+-3*SD)) | 4. Random Values
# In this we will mostly work on Numerical Values

# 1. If Normal Distribution -> use Mean | If skewed data then use -> Median (Use for < 5% missing data)

Working

In [8]:
import numpy as np
import pandas as pd
import matplotlib as plt
from sklearn.model_selection import train_test_split

In [9]:
data = pd.read_csv('titanic_toy.csv')
data.head(5)

    Age     Fare  Family  Survived
0  22.0   7.2500       1         0
1  38.0  71.2833       1         1
2  26.0   7.9250       0         1
3  35.0  53.1000       1         1
4  35.0   8.0500       0         0

In [10]:
data.info()
print("___________________________________")
data.isnull().sum()

<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Age       714 non-null    float64
 1   Fare      846 non-null    float64
 2   Family    891 non-null    int64
 3   Survived  891 non-null    int64
dtypes: float64(2), int64(2)
memory usage: 28.0 KB
___________________________________

Age         177
Fare         45
Family        0
Survived      0
dtype: int64

In [11]:
x = data.drop(columns=['Survived'])
y = data['Survived']

In [15]:
X_train, X_test, Y_train, Y_test = train_test_split(x, y, test_size=0.2, random_state=42)
X_train.isnull().mean()

Age       0.196629
Fare      0.050562
Family    0.000000
dtype: float64

In [17]:
# Find mean and median of Age and Fare
fare_mean = X_train['Fare'].mean()
fare_median = X_train['Fare'].median()

age_mean = X_train['Age'].mean()
age_median = X_train['Age'].median()

In [18]:
# Filling the values in Training Dataset
X_train['Fare_Mean'] = X_train['Fare'].fillna(fare_mean)
X_train['Fare_Median'] = X_train['Fare'].fillna(fare_median)

X_train['Age_Mean'] = X_train['Age'].fillna(age_mean)
X_train['Age_Median'] = X_train['Age'].fillna(age_median)

In [21]:
X_train.sample(10)

      Age      Fare  Family   Fare_Mean  Fare_Median   Age_Mean  Age_Median
484  25.0   91.0792       1   91.079200      91.0792  25.000000        25.0
517   NaN   24.1500       0   24.150000      24.1500  29.498846        28.0
371  18.0    6.4958       1    6.495800       6.4958  18.000000        18.0
133  29.0       NaN       1   32.517788      14.4000  29.000000        29.0
561  40.0    7.8958       0    7.895800       7.8958  40.000000        40.0
443  28.0   13.0000       0   13.000000      13.0000  28.000000        28.0
679  36.0  512.3292       1  512.329200     512.3292  36.000000        36.0
324   NaN   69.5500      10   69.550000      69.5500  29.498846        28.0
667   NaN    7.7750       0    7.775000       7.7750  29.498846        28.0
255  29.0   15.2458       2   15.245800      15.2458  29.000000        29.0

In [22]:
print("Fare variance original", X_train['Age'].var())

Fare variance original 210.2517072477435