In [2]:
print("Working")

Working

In [3]:
import numpy as np
import pandas as pd

In [4]:
data = pd.read_csv('data_science_job.csv')
data.head(5)

,enrollee_id,city,city_development_index,gender,relevent_experience,enrolled_university,education_level,major_discipline,experience,company_size,company_type,training_hours,target
0,8949,city_103,0.920,Male,Has relevent experience,no_enrollment,Graduate,STEM,20.0,NaN,NaN,36.0,1.0
1,29725,city_40,0.776,Male,No relevent experience,no_enrollment,Graduate,STEM,15.0,50-99,Pvt Ltd,47.0,0.0
2,11561,city_21,0.624,NaN,No relevent experience,Full time course,Graduate,STEM,5.0,NaN,NaN,83.0,0.0
3,33241,city_115,0.789,NaN,No relevent experience,NaN,Graduate,Business Degree,0.0,NaN,Pvt Ltd,52.0,1.0
4,666,city_162,0.767,Male,Has relevent experience,no_enrollment,Masters,STEM,20.0,50-99,Funded Startup,8.0,0.0

In [5]:
data.isnull().mean()*100

enrollee_id                0.000000
city                       0.000000
city_development_index     2.500261
gender                    23.530640
relevent_experience        0.000000
enrolled_university        2.014824
education_level            2.401086
major_discipline          14.683161
experience                 0.339284
company_size              30.994885
company_type              32.049274
training_hours             3.998330
target                     0.000000
dtype: float64

In [6]:
cols = [var for var in data.columns if data[var].isnull().mean() < 0.05 and data[var].isnull().mean() > 0]
cols

['city_development_index',
 'enrolled_university',
 'education_level',
 'experience',
 'training_hours']

In [7]:
len(data[cols].dropna()) / len(data)

0.8968577095730244

In [8]:
new_data = data[cols].dropna()
data.shape, new_data.shape

((19158, 13), (17182, 5))

### Removing from Categorical Columns

In [9]:
data['enrolled_university'].value_counts()

temp = pd.concat([
    # Original 
    data['enrolled_university'].value_counts() / len(data),

    # CCA (Complete Case Analysis)
    new_data['enrolled_university'].value_counts() / len(new_data)
], axis=1)

temp.columns = ['Original', 'CCA']
temp

# In the result we noiced that there is no big change on the data
# so it wont cause any issue, if the values would be a bit more affected the CCA is not good option

                     Original       CCA
enrolled_university
no_enrollment        0.721213  0.735188
Full time course     0.196106  0.200733
Part time course     0.062533  0.064079

In [10]:
# Applying on different cat column
data['education_level'].value_counts()

temp2 = pd.concat([
    # Original
    data['education_level'].value_counts() / len(data),

    # CCA
    new_data['education_level'].value_counts() / len(new_data)
], axis=1)

temp2.columns = ['Original', 'CCA']
temp2

                 Original       CCA
education_level
Graduate         0.605387  0.619835
Masters          0.227633  0.234082
High School      0.105282  0.107380
Phd              0.021610  0.022116
Primary School   0.016077  0.016587