In [2]:
import numpy as np
import pandas as pd

In [3]:
date = pd.read_csv('orders.csv')
time = pd.read_csv('messages.csv')

## Working with Dates

In [7]:
date['date'] = pd.to_datetime(date['date'])

### 1. Extract Year

In [8]:
date['date_year'] = date['date'].dt.year
date.sample()

         date  product_id  city_id  orders  date_year
69 2018-12-28        2652       18      84       2018

### 2. Extract Month

In [11]:
date['date_month'] = date['date'].dt.month
date['date_month_name'] = date['date'].dt.month_name()
date.sample()

,date,product_id,city_id,orders,date_year,date_month,date_month_name
627,2018-08-01,4568,13,138,2018,8,August

### 3. Extract Days

In [21]:
date['date_days'] = date['date'].dt.day

# Day of week
date['date_days_week'] = date['date'].dt.day_of_week

# Day of week name
date['day_week_name'] = date['date'].dt.day_name()

# Is weekend??
date['isWeekend'] = np.where(date['day_week_name'].isin(["Sunday", "Saturday"]), 1, 0)
date.sample()

,date,product_id,city_id,orders,date_year,date_month,date_month_name,date_days,date_days_week,day_week_name,isWeekend
612,2019-01-26,7354,25,2,2019,1,January,26,5,Saturday,1

### 4. Extract Week of Year

In [29]:
date['date_week'] = date['date'].dt.day_of_week
date.sample()

,date,product_id,city_id,orders,date_year,date_month,date_month_name,date_days,date_days_week,day_week_name,isWeekend,date_week
902,2019-03-24,5031,0,6,2019,3,March,24,6,Sunday,1,6

### 5. Extract Quarter

In [41]:
date['quarter'] = date['date'].dt.quarter
date.sample()

# Extract Semester using Quarter
date['semester'] = np.where(date['quarter'].isin([1, 2]), 1, 2)
date.sample()

,date,product_id,city_id,orders,date_year,date_month,date_month_name,date_days,date_days_week,day_week_name,isWeekend,date_week,quarter,semester
769,2019-08-09,408,9,2,2019,8,August,9,4,Friday,0,4,3,2

## Working wiht Time

In [44]:
time.info()
time['date'] = pd.to_datetime(time['date'])

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   str
 1   msg     1000 non-null   str
dtypes: str(2)
memory usage: 15.8 KB

In [45]:
time['hour'] = time['date'].dt.hour
time['minutes'] = time['date'].dt.minute
time['seconds'] = time['date'].dt.second

### 1. Extract Time part

In [47]:
time['time'] = time['date'].dt.time
time.head()

,date,msg,hour,minutes,seconds,time
0,2013-12-15 00:50:00,ищу на сегодня мужика 37,0,50,0,00:50:00
1,2014-04-29 23:40:00,ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826,23,40,0,23:40:00
2,2012-12-30 00:21:00,Днепр.м 43 позн.с д/ж *.о 067.16.34.576,0,21,0,00:21:00
3,2014-11-28 00:31:00,КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...,0,31,0,00:31:00
4,2013-10-26 23:11:00,Зая я тебя никогда не обижу люблю тебя!) Даше,23,11,0,23:11:00

### 2. Time difference

In [69]:
import datetime
today = datetime.datetime.today()
today

# In Days
today - time['date']

# In Seconds
(today - time['date'])/np.timedelta64(1, 's')

# In Minutes
(today - time['date'])/np.timedelta64(1, 'm')

# In Hours
(today - time['date'])/np.timedelta64(1, 'h')

# Here timedelta64 tells the difference between the time interval (duration between 2 time)

0      107584.708735
1      104321.875402
2      115985.192069
3       99233.025402
4      108762.358735
           ...
995    122920.708735
996    106626.308735
997    117785.925402
998    120569.975402
999    103098.125402
Name: date, Length: 1000, dtype: float64